config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :reviews
  resources :request_images
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :users do
    get 'profile', to: 'users#show'
    get 'edit_profile', to: 'users#edit'
  end

  resources :sellers do
    collection do
      get 'dashboard', to: 'sellers#dashboard'
      get 'proposals', to: 'sellers#proposals'
    end
  end

  resources :customers do
    collection do
      get 'dashboard', to: 'customers#dashboard'
      get 'proposals', to: 'customers#proposals'
    end
  end

  resources :services do
    collection do
      get 'categories', to: 'services#categories'
      get '/area/:area', to: 'services#area', as: :area
      get '/area/:area/:category', to: 'services#category', as: :category
      get 'search', to: 'services#search'
    end
  end

  resources :requests do
    collection do
      get 'owner', to: 'requests#owner'
    end
    member do 
      get 'proposals', to: 'requests#proposals'
    end
  end
  resources :request_images

  resources :businesses
  resources :messages do
    collection do
      get 'conversations', to: 'messages#conversations'
      get 'conversations/:id', to: 'messages#conversations'
    end
  end

  resources :job_offers do
    member do
      post 'accept', to: 'job_offers#accept'
    end
  end

  resources :proposals do
    collection do
      get 'owner', to: 'proposals#owner'
    end
    member do
      post 'book', to: 'proposals#book'
    end
  end

  resources :reviews
  resources :notifications

  get '/how-it-works', to: 'pages#how_it_works'
  root :to => 'pages#home'
end

app/models/conversation.rb
class Conversation
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :messages
  has_and_belongs_to_many :users
  belongs_to :proposal
  belongs_to :request

  field :messages_count, type: Fixnum, default: 0
  field :messaged_at, type: DateTime
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.where(:user_ids.in => [current_user.id], :messages_count.gt => 0)
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.fetch(:conversation, {})
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_for(conversation) do |f| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conversations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>