config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :reviews
  resources :request_images
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :users do
    get 'profile', to: 'users#show'
    get 'edit_profile', to: 'users#edit'
  end

  resources :sellers do
    collection do
      get 'dashboard', to: 'sellers#dashboard'
      get 'proposals', to: 'sellers#proposals'
    end
  end

  resources :customers do
    collection do
      get 'dashboard', to: 'customers#dashboard'
      get 'proposals', to: 'customers#proposals'
    end
  end

  resources :services do
    collection do
      get 'categories', to: 'services#categories'
      get '/area/:area', to: 'services#area', as: :area
      get '/area/:area/:category', to: 'services#category', as: :category
      get 'search', to: 'services#search'
    end
  end

  resources :requests do
    collection do
      get 'owner', to: 'requests#owner'
    end
    member do 
      get 'proposals', to: 'requests#proposals'
    end
  end
  resources :request_images

  resources :businesses
  resources :messages do
    collection do
      get 'conversations', to: 'messages#conversations'
      get 'conversations/:id', to: 'messages#conversations'
    end
  end

  resources :job_offers do
    member do
      post 'accept', to: 'job_offers#accept'
    end
  end

  resources :proposals do
    collection do
      get 'owner', to: 'proposals#owner'
    end
    member do
      post 'book', to: 'proposals#book'
    end
  end

  resources :reviews
  resources :notifications

  get '/how-it-works', to: 'pages#how_it_works'
  root :to => 'pages#home'
end

app/models/request.rb
class Request
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
  belongs_to :service
  has_many :proposals
  has_many :answers
  has_many :messages
  has_many :request_images
  has_one :job_offer

  field :title,                 type: String
  field :description,           type: String
  field :location,              type: String
  field :max_price,             type: Integer, default: 0
  field :min_price,             type: Integer, default: 0
  field :payment_mode,          type: String
  field :job_completion,        type: String
  field :job_completion_unit,   type: String
  field :specifics,             type: String
  field :start_date,            type: Date
  field :done,                  type: Boolean, default: false
  field :status,                type: String, default: 'active' # active, pending, expired, done
  field :has_accepted_proposal,     type: Boolean, default: false 

  validates :location, presence: true
  validates :status, presence: true, inclusion: { in: ['active', 'pending', 'expired', 'done'] }
  validates :payment_mode, presence: true, inclusion: { in: ['single', 'hourly', 'daily', 'monthly'] }
  validate :validate_request_images

  after_create :email_request_completion

  def accepted_proposal
    proposals.where(:accepted => true).first
  end

  def validate_request_images
    errors.add(:request_images, "too much") if request_images.size > 3
  end

  def email_request_completion
    RequestMailer.request_completion(self).deliver
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :create_user, only: [:create]
  before_action :set_request, only: [:show, :edit, :update, :destroy, :proposals]
  after_action  :save_images, only: [:update, :create]

  # GET /requests
  # GET /requests.json
  def index
    if params['commit'] == 'Search'
      @service_ids = Service.where(:category => params[:service].downcase).pluck(:id)
      @other_requests = Request.where(search_params)
    else
      @other_requests = Request.all
    end

    @other_requests = @other_requests.where(:user_id.ne => current_user.id) if current_user
  end

  def owner
    @my_requests = current_user.requests
    @recommended_services =  Service.limit(10)
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
    @request.service = Service.where(:type => params[:service_type]).first || not_found
    @request.build_user if !current_user
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  # TODO register user here
  def create
    @request = @user.requests.new(request_params)

    respond_to do |format|
      form_valid = @user.valid? && @request.valid?

      if form_valid && @request.save
        sign_in @user

        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        @request.user = @user
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def proposals
    @proposals = @request.proposals
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def request_params
    params.require(:request).permit(:service_id, :location, :title, :description, :min_price, :max_price, :start_date, :job_completion, :job_completion_unit, :payment_mode)
  end

  def create_user
    if current_user
      @user = current_user
      @user.is_customer = true
      @user.current_role = 'customer'
    else
      @user = User.new(params[:request].require(:user).permit(:first_name, :last_name, :email, :phone, :password).merge(is_customer: true, current_role: 'customer'))
    end
  end

  def save_images
    return if !@request.valid?
    (params[:request][:images] || []).each do |image|
      ri = @request.request_images.new
      ri.image = image
      ri.save
    end
  end

  def search_params
    query = {}
    query.merge!( :service_id.in => @service_ids ) if params[:service].present?
    query.merge!( :location => params[:location] ) if params[:location].present?
    query
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<div class=''>
  <%= form_for(request) do |f| %>
    <% if request.errors.any? %>
      <div id="error_explanation">
        <h4><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h4>

        <ul>
          <% request.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field(:service_id) %>

    <div class='input-field js-location-input-container'>
      <%= f.label :location %>
      <input type="text" name="" value="<%= f.object.location %>" id="js-modal-button", autocomplete='off', readonly='true' class='js-location-input'>
      <%= f.text_field :location, class: 'hidden js-location-input' %>
    </div>

    <div class='row'>
      <div class='input-field col s6 m3'>
        <%= f.select :min_price do %>
          <% [0, 250, 500, 1000, 3000, 5000, 7_000, 10_000, 15_000, 20_000].each do |c| -%>
            <%= content_tag(:option, (c.zero? ? 'Any' : number_to_currency(c, unit: '', precision: 0)), value: c) %>
          <% end %>
        <% end %>
        <label for="Min Price (PHP)">Min Price (PHP)</label>
      </div>

      <div class='input-field col s6 m3'>
        <%= f.select :max_price do  %>
          <% [0, 250, 500, 1000, 3000, 5000, 7_000, 10_000, 15_000, 20_000].each do |c| -%>
            <%= content_tag(:option, (c.zero? ? 'Any' : number_to_currency(c, unit: '', precision: 0)), value: c) %>
          <% end %>
        <% end  %>
        <label for="Max Price (PHP)">Max Price (PHP)</label>
      </div>

      <div class='input-field col s12 m6'>
        <%= f.select :payment_mode do %>
          <% [['One-time Payment', 'single'], ['Hourly', 'hourly'], ['Daily', 'daily'], ['Monthly', 'monthly']].each do |c| -%>
            <%= content_tag(:option, c.first, value: c.last) %>
          <% end %>
        <% end %>
        <label for="Payment mode">Payment mode</label>
      </div>
    </div>

    <div class='row'>
      <div class='input-field col s6 m6'>
        <%= f.select(:job_completion)  do %>
          <% (0..20).each do |c| -%>
            <%= content_tag(:option, (c.zero? ? 'Any' : c), value: c) %>
          <% end %>
        <% end %>
        <%= f.label :job_completion %>
      </div>
      <div class='input-field col s6 m6'>
        <%= f.select(:job_completion_unit)  do %>
          <% [['Days', 'day'], ['Months', 'month']].each do |c| -%>
            <%= content_tag(:option, c.first, value: c.last) %>
          <% end %>
        <% end %>
        <label for="job_completion_unit">Days/Months</label>
      </div>
    </div>

    <p class=''>
      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'datepicker' %>
    </p>

    <div class='input-field'>
      <label for="">Details</label>
      <%= f.text_area :description, class: 'materialize-textarea', placeholder: 'Add specific details about your request.' %>
    </div>

    <% request.request_images.each do |ri| %>
      <div>
        <%= image_tag ri.image.url  %>
        <%= link_to 'Delete', request_image_path(ri), method: :delete %>
      </div>
    <% end %>

    <div class='file-field input-field'>
      <div class='btn'>
        <i class='medium material-icons'> add_a_photo </i>
        <%= f.file_field :images, multiple: true %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="Upload images">
      </div>
    </div>

    <% if !current_user %>
      <% if request.user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(request.user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% request.user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.fields_for request.user do |user| %>
        <div class='input-field'>
          <%= user.label :first_name  %>
          <%= user.text_field :first_name %>
        </div>


        <div class='input-field'>
          <%= user.label :last_name %>
          <%= user.text_field :last_name %>
        </div>


        <div class='input-field'>
          <%= user.label :phone %>
          <%= user.text_field :phone %>
        </div>


        <div class='input-field'>
          <%= user.label :email %>
          <%= user.text_field :email %>
        </div>


        <div class='input-field'>
          <%= user.label :password %>
          <%= user.password_field :password %>
        </div>

      <% end %>
    <% end %>

    <div class="actions">
      <%= f.submit 'Send', class: 'btn col s12 m3 btn-large' %>
    </div>
  <% end %>

</div>
<%= render 'partials/locations_modal' %>

app/views/requests/_guest_request.html.erb
<div class=''>
  <div class='card small'>
    <div class='card-content'>
      <p class='looking-for-text grey-text'><i class='material-icons grey-text small'>record_voice_over</i> Looking for</p>
      <h5>  <%= request.service.type.capitalize %></h5>
      <strong><p><span class='grey-text'>in </span> <%= request.location %>  </p></strong>
      <strong><p> <span class='grey-text'> for  </span> PHP <%= number_to_currency(request.min_price, unit: '') %> - <%= number_to_currency(request.max_price, unit: '') %>  </p></strong>
      <strong><span class='grey-text'> Needed on </span> <%= request.start_date %></strong>
      <br />
    </div>
    <div class='card-action '>
      <span class='grey-text left'><%= request.created_at.to_formatted_s(:short) if request.created_at %></span>
      <div class='right'>
        <% if request.job_offer %>
          <p class='green-text'>ALREADY HIRED SOMEONE</p>
        <% else %>

          <% if current_user %>
            <% if current_user.business && current_user.business.proposal(request).nil? %>
              <%= link_to "Apply", new_proposal_path(request_id: request.id), class: 'btn ' %>
            <% elsif current_user.business  %>
              <%= link_to 'Proposal Submitted', proposal_path(current_user.business.proposal(request)), style: 'margin-right:0px;' %>
            <% else %>
              <%= link_to "Apply", new_business_path(request_id: request.id), class: 'btn ' %>
            <% end %>
          <% else %>
            <%= link_to "Apply", new_business_path(request_id: request.id), class: 'btn ' %>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/requests/_owner_request.html.erb
<div class='col s12 m12'>
  <div class='card small'>
    <div class='card-content'>
      <span class='card-title '><%= request.service.type.capitalize %> <span class='grey-text'>in</span> <%= request.location %></span>
      <p> <%= request.created_at.to_formatted_s(:short) if request.created_at %> </p>
      <% if request.proposals.count > 0 %>
        <strong class='grey-text'> <%= request.proposals.count %> proffesionals has reached out to you. </strong>
        <br />
        <% request.proposals.each do |proposal| %>
          <div class="chip">
            <%= image_tag proposal.business.image_url %>
            <%= proposal.business.name %>
          </div>
        <% end %>
      <% else %>
        <strong class='grey-text'> Reaching out to proffesionals</strong>
      <% end %>
      <% if request.job_offer %>
        <br />
        <br />
        <% if request.job_offer.status == 'pending' %>
          <%= link_to "Pending job offer for #{request.job_offer.proposal.business.name}", job_offer_path(request.job_offer) %>
        <% elsif request.job_offer.status == 'active'  %>
          <%= link_to "Hired #{request.job_offer.proposal.business.name}", proposal_path(request.job_offer.proposal) %>
        <% end %>

      <% end %>
    </div>

    <div class='card-action'>
      <% if request.proposals.count > 0 %>
        <%= link_to "View", proposals_request_path(request) %>
      <% else %>
        <%= link_to "View", request_path(request) %>
      <% end %>
    </div>

  </div>
</div>

app/views/requests/edit.html.erb
<div class='container section'>
  <h4 class='text-thin col s12 m12'>Editing Request</h4>

  <%= render 'form', request: @request %>

  <%= link_to 'Show', @request %> |
  <%= link_to 'Back', requests_path %> 
</div>

app/views/requests/index.html.erb
<div class='container others-requests'>
  <% if current_user %>
    <div class='row section'>
      <div class='col s12 m12'>
        <div class='tabs tab-redirect card'>
          <li class="tab col s3"><%= link_to 'My Requests', owner_requests_path %></li>
          <li class="tab col s3 active"><%= link_to 'Customers Request', requests_path, class: 'active' %></li>
        </div>
      </div>
    </div>
  <% end %>

  <div class='row section search-form-section'>
    <%= form_tag requests_path, method: :get do %>
      <div class='input-field js-location-input-container col m4 s12'>
        <i class="material-icons prefix">place</i>
        <label for="js-modal-button">Location</label>
        <input type="text" name="" value="<%= params[:location] %>" id="js-modal-button", autocomplete='off', readonly='true' class='js-location-input'>
        <%= text_field_tag :location, params[:location], class: 'hidden js-location-input' %>
      </div>


      <div class='input-field col m5 s12'>
        <%= react_component('services/autoCompleteServiceInput', { value: params[:service] }, class: 'input') %>
      </div>


      <div class='input-field col m3 s12'>
        <%= submit_tag 'Search', class: 'btn col s12' %>
      </div>
    <% end %>
  </div>

  <div class='row other-request-section section'>
    <% @other_requests.each do |request| %>
      <div class='col s12 m6'>
        <%= render 'guest_request', request: request %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'partials/locations_modal' %>

app/views/requests/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col s12 m12'>
      <div class="card horizontal">
        <div class="card-image">
          <%= image_tag @request.service.image.url, style: 'width: 120px; min-height: 120px;' %>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <strong>Request  <span class='grey-text'> for </span> <%= params[:service_type] %> service</strong>
          </div>
        </div>
      </div>
    </div>
    <div class='col s12 m12'>
      <br />
      <%= render 'form', request: @request %>
    </div>


  </div>
</div>

app/views/requests/owner.html.erb
<div class='container my-requests'>
  <div class='row section'>
    <div class='col s12 m12'>
      <div class='tabs tab-redirect card'>
        <li class="tab col s3 active"><%= link_to 'My Requests', owner_requests_path, class: 'active' %></li>
        <li class="tab col s3"><%= link_to 'Customers Request', requests_path %></li>
      </div>
    </div>
  </div>

  <div class='row requests-section section'>
    <div class='row'>
      <% @my_requests.each do |request| %>
        <div class='col s12 m6'>
          <%= render 'owner_request', request: request %>
        </div>
      <% end %>
    </div>
  </div>

  <div class='recommended-section section'>
    <h5 class='teal-text'>Do you also need?</h5>
    <div class='row'>
      <% @recommended_services.each do |service| %>
        <div class='col m4 s12'>
          <%= link_to new_request_path(service_type: service.type) do %>
            <div class='card hoverable'>
              <div class='card-image'>
                <%= image_tag service.image.url %>
                <span class='card-title'><%= service.type.capitalize %></span>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/requests/proposals.html.erb
<div class='container customer-proposals'>
  <% breadcrumb :request_proposals, @request %>


  <ul class="collection">
    <% @proposals.each do |proposal| %>
      <%= link_to proposal_path(proposal), class: 'collection-item avatar' do %>
        <%= image_tag proposal.business.image_url, class: 'circle responsive-img' %>
        <strong class="title"><%= proposal.business.name %></strong>
        <p class='grey-text'>
          <%= proposal.business.user.complete_name %>
          <br />
          <%= proposal.messages.count %>
          <i class='material-icons'>message</i>

        </p>

        <div class="secondary-content">
          <strong>PHP <%= number_to_currency(proposal.price_quotation, unit: '') %></strong>
          <div class='content grey-text'>Done within <%= proposal.job_delivery_estimate %> <%= proposal.job_delivery_estimate_unit %></div>
          <div class='grey-text'>
            <% if proposal.job_offer %>
              <span class='green-text'> ACCEPTED </span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>

</div>

app/views/requests/show.html.erb
<div class='container'>
  <div class='whats-next-section'>
    <h4 class='text-thin'>Whats next?</h4>
    <p> Your request has been completed. Thank you for posting! </p>
    <p> Users around you can soon view and respond to your request. To be most secured, please conduct all communications through our messaging system. </p>
  </div>

  <div class='request-summary-section section'>
    <h4 class='text-thin'>Request Summary</h4>

    <label for="">Location</label>
    <p><%= @request.location %></p>
    <label for="">Details</label>
    <p><%= @request.description %></p>
    <label for="">Start Date</label>
    <p><%= @request.start_date %></p>
    <label for="Price Range">Price Range</label>
    <p><%= "PHP #{number_to_currency(@request.min_price, unit: '', precision: 0)} - #{number_to_currency(@request.max_price, unit: '', precision: 0)}" %></p>
    <label for="">Job Completion</label>
    <p><%= "#{@request.job_completion} #{@request.job_completion_unit}" %></p>

    <% @request.request_images.each do |rm| %>
      <%= image_tag rm.image.url %>
    <% end %>
  </div>

  <div class='center-align'>
    <%= link_to 'Edit request', edit_request_path(@request) %> | <%= link_to 'View your requests', owner_requests_path %>
    <br />
  </div>

</div>