config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :reviews
  resources :request_images
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :users do
    get 'profile', to: 'users#show'
    get 'edit_profile', to: 'users#edit'
  end

  resources :sellers do
    collection do
      get 'dashboard', to: 'sellers#dashboard'
      get 'proposals', to: 'sellers#proposals'
    end
  end

  resources :customers do
    collection do
      get 'dashboard', to: 'customers#dashboard'
      get 'proposals', to: 'customers#proposals'
    end
  end

  resources :services do
    collection do
      get 'categories', to: 'services#categories'
      get '/area/:area', to: 'services#area', as: :area
      get '/area/:area/:category', to: 'services#category', as: :category
      get 'search', to: 'services#search'
    end
  end

  resources :requests do
    collection do
      get 'owner', to: 'requests#owner'
    end
    member do 
      get 'proposals', to: 'requests#proposals'
    end
  end
  resources :request_images

  resources :businesses
  resources :messages do
    collection do
      get 'conversations', to: 'messages#conversations'
      get 'conversations/:id', to: 'messages#conversations'
    end
  end

  resources :job_offers do
    member do
      post 'accept', to: 'job_offers#accept'
    end
  end

  resources :proposals do
    collection do
      get 'owner', to: 'proposals#owner'
    end
    member do
      post 'book', to: 'proposals#book'
    end
  end

  resources :reviews
  resources :notifications

  get '/how-it-works', to: 'pages#how_it_works'
  root :to => 'pages#home'
end

app/models/proposal.rb
class Proposal
  include Mongoid::Document
  include Mongoid::Timestamps
  include PublicActivity::Common

  belongs_to :request
  belongs_to :business
  has_many :messages
  has_one :job_offer
  has_one :conversation

  field :price_quotation,               type: Integer
  field :payment_mode,                  type: String
  field :job_delivery_estimate,         type: String
  field :job_delivery_estimate_unit,    type: String
  field :message,                       type: String
  field :booked,                        type: Boolean, default: false
  field :status,                        type: String, default: 'active' #active, pending, expired, done
  field :accepted,                      type: Boolean, default: false

  validates :message, presence: true
  validates :status, presence: true, inclusion: { in: ['active', 'pending', 'expired', 'done'] }
  validates :payment_mode, presence: true, inclusion: { in: ['single', 'hourly', 'daily', 'monthly'] }
  validates :job_delivery_estimate_unit, presence: true, inclusion: { in: ['hours', 'days', 'months'] }

  after_create :email_proposal_sent,
    :create_conversation,
    :create_notification

  def create_conversation
    return if self.conversation
    self.build_conversation(request: request).save!
    self.conversation.users << business.user
    self.conversation.users << request.user
  end

  def create_notification
    self.create_activity(:create, owner: business.user, recipient: request.user, recipient_read: false)
  end

  def email_proposal_sent
    ProposalMailer.proposal_sent(self).deliver
    RequestMailer.proposal_received(self).deliver
  end

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy, :book]

  # GET /proposals
  # GET /proposals.json
  def index
    request_ids = current_user.requests.pluck(:id)
    @offered_proposals = Proposal.where(:request_id.in => request_ids)
  end

  def owner
    @my_proposals = current_user.business ? current_user.business.proposals : []
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @request = @proposal.request
    @business = @proposal.business
    @message = Message.new
    @messages = Message.where(:proposal_id => @proposal.id, :request_id => @request.id)
  end

  # GET /proposals/new
  def new
    @request = Request.find(params[:request_id])
    @proposal = @request.proposals.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @request = Request.find(params[:proposal][:request_id])
    @proposal = @request.proposals.new(proposal_params)
    @business = current_user.business

    @proposal.business = @business

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Notify seller about his/her proposal being accepted
  def book
    @request = @proposal.request

    @proposal.accepted = true
    @request.has_accepted_proposal = true

    respond_to do |format|
      if (@proposal.save && @request.save)
        format.html { redirect_to proposal_url(@proposal), notice: 'Proposal was successfully booked.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, notice: 'Error booking proposal' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.fetch(:proposal, {}).permit(:message, :price_quotation, :payment_mode, :job_delivery_estimate, :job_delivery_estimate_unit)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<div class='row'>
  <%= form_for(proposal) do |f| %>
    <%= f.hidden_field :request_id %>
    <% if proposal.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(proposal.errors.count, "error") %> prohibited this proposal from being saved:</p>

        <ul>
          <% proposal.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='input-field col s6 m6'>
      <%= f.label :price_quotation, 'Price Quotation (PHP)' %>
      <%= f.text_field :price_quotation, autofocus: true %>
    </div>

    <div class='input-field col s6 m6'>
      <%= f.select :payment_mode, class: 'select' do %>
        <% [['One-time Payment', 'single'], ['Hourly', 'hourly'], ['Daily', 'daily'], ['Monthly', 'monthly']].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
      <%= f.label :payment_mode %>
    </div>

    <div class='input-field col s6 m6'>
      <%= f.select :job_delivery_estimate do %>
        <% (0..29).each do |c| -%>
          <%= content_tag(:option, (c.zero? ? 'Any' : number_to_currency(c, unit: '', precision: 0)), value: c) %>
        <% end %>
      <% end %>
      <%= f.label :job_delivery_estimate %>
    </div>

    <div class='input-field col s6 m6'>
      <%= f.select :job_delivery_estimate_unit do %>
        <% [['Days', 'days'], ['Hours', 'hours'], ['Months', 'months']].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
      <%= f.label :job_delivery_estimate_unit, 'Hours/Days/Months' %>
    </div>

    <div class='input-field col s12'>
      <%= f.label :message %>
      <%= f.text_area :message, class: 'materialize-textarea' %>
    </div>



    <div class="input-field col s12">
      <%= f.submit 'Submit', class: 'btn btn-large col s12 m6 l6' %>
    </div>
  <% end %>
</div>

app/views/proposals/_guest_proposal.html.erb
<% proposals.each do |proposal| %>
  <% request = proposal.request %>
  <div class='card'>
    <div class='card-content'>
      <strong><%= request.service.type.capitalize %></strong>
      <span class='right'><%= request.created_at.to_formatted_s(:short) if request.created_at %></span>
      <p> <%= request.location %>  </p>
      <br />
      <%= number_to_currency(proposal.price_quotation, unit: 'PHP') %>
      <%= proposal.payment_mode %> payment

      <p>
        Complete within
        <%= proposal.job_delivery_estimate %>
        <%= proposal.job_delivery_estimate_unit %>
      </p>

      <br />

    </div>
    <div class='card-action'>
      <%= link_to "View Proposal", proposal_path(proposal) %>
    </div>
  </div>
<% end %>

app/views/proposals/_owner_proposal.html.erb
<% proposals.each do |proposal| %>
  <% request = proposal.request %>
  <div class='card'>
    <div class='card-content'>
      <strong><%= request.service.type.capitalize %></strong>
      <span class='right'><%= request.created_at.to_formatted_s(:short) if request.created_at %></span>
      <p> <%= request.location %>  </p>
      <br />
      <%= number_to_currency(proposal.price_quotation, unit: 'PHP') %>
      <%= proposal.payment_mode %> payment

      <p>
        Complete within
        <%= proposal.job_delivery_estimate %>
        <%= proposal.job_delivery_estimate_unit %>
      </p>

      <br />
      <% if proposal.job_offer %>
          <% msg = proposal.job_offer.is_accepted ? 'JOB OFFER ACCEPTED' : 'This proposal has received a JOB OFFER'%>
          <strong class='teal-text'> <%= link_to msg, job_offer_path(proposal.job_offer) %></strong>
      <% end %>

    </div>
    <div class='card-action'>
      <%= link_to "View Proposal", proposal_path(proposal) %>
    </div>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing Proposal</h1>

<%= render 'form', proposal: @proposal %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<div class='container'>

  <div class='row section'>
    <div class='col s12 m12'>
      <div class='tabs tab-redirect card'>
        <li class="tab col s3 "><%= link_to 'My Proposals', owner_proposals_path %></li>
        <li class="tab col s3 active"><%= link_to 'Proposal for me', proposals_path, class: 'active' %></li>
      </div>
    </div>
  </div>

  <div class='offered-proposals-section'>
    <%= render 'guest_proposal', proposals: @offered_proposals %>
  </div>

</div>

app/views/proposals/new.html.erb
<% breadcrumb :new_proposal, @proposal %>

<div class='container proposal-show'>
  <div class='row'>
    <div class='col s12 m6 request-details'>
      <div class='col s12 m2 request-image'>
        <%= image_tag @request.user.avatar_url, class: 'circle responsive-img' %>
      </div>
      <div class='col s12 m10'>
        <p class='request-title'>
        <%= @request.user.complete_name %> <span class='grey-text'> is looking for </span><br /> <%= @request.service.type.capitalize %>
        </p>
      </div>
      <div class='clearfix'> </div>

      <strong><p><span class='grey-text'>in </span> <%= @request.location %>  </p></strong>
      <strong><p> <span class='grey-text'> for  </span> PHP <%= number_to_currency(@request.min_price, unit: '') %> - <%= number_to_currency(@request.max_price, unit: '') %>  </p></strong>
      <strong><span class='grey-text'> Needed on </span> <%= @request.start_date %></strong>
      <br />
      <br />
      <p><%= @request.description %></p>
    </div>

    <div class='col s12 m6'>
      <h4>Proposal</h4>
      <%= render 'form', proposal: @proposal %>
    </div>
  </div>
</div>

app/views/proposals/owner.html.erb
<div class='container'>

  <div class='row section'>
    <div class='col s12 m12'>
      <div class='tabs tab-redirect card'>
        <li class="tab col s3 active"><%= link_to 'My Proposals', owner_proposals_path, class: 'active' %></li>
        <li class="tab col s3"><%= link_to 'Proposal for me', proposals_path %></li>
      </div>
    </div>
  </div>

  <div class='offered-proposals-section'>
    <div class='row'>
      <div class=' col s12 m12 right-align'>
        <%= link_to 'Search for customers', requests_path, class: ' btn' %>
      </div>
    </div>
    <%= render 'owner_proposal', proposals: @my_proposals %>
  </div> 

</div>

app/views/proposals/show.html.erb
<% breadcrumb :show_proposal, @proposal %>

<div class='container proposal-show'>
  <% if @proposal.job_offer && @proposal.request.user == current_user %>
    <div class="col s12 m12">
      <div class="card-panel teal">
        <span class="white-text">
          We have notified the service provider of your booking. You can contact the service provider or message him below for more details.
        </span>
      </div>
    </div>
  <% end %>

  <div class='row col s12 m12 section'>
    <div class='col s12 m6 request-details'>
      <div class='col s12 m2 request-image'>
        <%= image_tag @request.user.avatar_url, class: 'circle responsive-img' %>
      </div>
      <div class='col s12 m10'>
        <p class='request-title'>
          <%= @request.user.complete_name %> <span class='grey-text'> is looking for </span><br /> <%= @request.service.type.capitalize %>
        </p>
      </div>
      <div class='clearfix'> </div>

      <strong><p><span class='grey-text'>in </span> <%= @request.location %>  </p></strong>
      <strong><p> <span class='grey-text'> for  </span> PHP <%= number_to_currency(@request.min_price, unit: '') %> - <%= number_to_currency(@request.max_price, unit: '') %>  </p></strong>
      <strong><span class='grey-text'> Needed on </span> <%= @request.start_date %></strong>
      <br />
      <br />
      <p><%= @request.description %></p>
    </div>

    <div class='card col s12 m6 proposal-details'>
      <div class='col s12 m12'>
        <h4 class='text-thin'>Proposal</h4>
        <span class='business-name'><%= @business.name %></span>
      </div>
      <div class='col s12 m4'>
        <%= image_tag @business.image_url, class: 'responsive-img' %>
      </div>
      <div class='col s12 m8'>
        <p> <i class='material-icons'>person</i> <%= @business.user.complete_name %></p>
        <p> <i class='material-icons'>email</i> <%= @business.user.email %></p>
      </div>

      <div class='col s12 m12'>
        <strong for="">Price Quote </strong>
        <p> <%= number_to_currency(@proposal.price_quotation, unit: 'PHP') %> (<%= @proposal.payment_mode %> payment)</p>

        <strong for="Job delivery estimate">Job delivery estimate</strong>
        <p><%= @proposal.job_delivery_estimate %> <%= @proposal.job_delivery_estimate_unit %></p>

        <strong for="Message">Message</strong>
        <p><%= @proposal.message %></p>  
      </div>
      
    </div>
  </div>

  <div class='row'>
    <div class='col s12 m12'>
      <ul>
        <% @messages.each do |msg| %>
          <li>
            <div class="<%= msg.user == current_user ? 'right-align' : 'left-align' %>">
              <%= render msg, message: msg %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class='col s12 m12'>
      <%= render 'messages/form', message: @message, proposal: @proposal %>
    </div>
  </div>

</div>