config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :reviews
  resources :request_images
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :users do
    get 'profile', to: 'users#show'
    get 'edit_profile', to: 'users#edit'
  end

  resources :sellers do
    collection do
      get 'dashboard', to: 'sellers#dashboard'
      get 'proposals', to: 'sellers#proposals'
    end
  end

  resources :customers do
    collection do
      get 'dashboard', to: 'customers#dashboard'
      get 'proposals', to: 'customers#proposals'
    end
  end

  resources :services do
    collection do
      get 'categories', to: 'services#categories'
      get '/area/:area', to: 'services#area', as: :area
      get '/area/:area/:category', to: 'services#category', as: :category
      get 'search', to: 'services#search'
    end
  end

  resources :requests do
    collection do
      get 'owner', to: 'requests#owner'
    end
    member do 
      get 'proposals', to: 'requests#proposals'
    end
  end
  resources :request_images

  resources :businesses
  resources :messages do
    collection do
      get 'conversations', to: 'messages#conversations'
      get 'conversations/:id', to: 'messages#conversations'
    end
  end

  resources :job_offers do
    member do
      post 'accept', to: 'job_offers#accept'
    end
  end

  resources :proposals do
    collection do
      get 'owner', to: 'proposals#owner'
    end
    member do
      post 'book', to: 'proposals#book'
    end
  end

  resources :reviews
  resources :notifications

  get '/how-it-works', to: 'pages#how_it_works'
  root :to => 'pages#home'
end

app/models/job_offer.rb
class JobOffer
  include Mongoid::Document
  include Mongoid::Timestamps
  include PublicActivity::Common

  belongs_to :proposal
  belongs_to :request

  field :agreed_job_completion,         type: Integer
  field :agreed_job_completion_unit,    type: String
  field :agreed_price,                  type: Integer
  field :agreed_payment_mode,           type: String
  field :order_id,                      type: String
  field :message,                       type: String
  field :status,                        type: String, default: 'pending'
  field :is_accepted,                   type: Boolean, default: false
  field :accepted_at,                   type: DateTime

  validates :status, presence: true, inclusion: { in: ['pending', 'active', 'expired', 'done'] }
  validates :agreed_job_completion_unit, inclusion: { in: ['hours', 'days', 'months'] }, allow_blank: true
  validates :agreed_payment_mode, inclusion: { in: ['single', 'hourly', 'daily', 'monthly'] }, allow_blank: true

  def accept!
    self.is_accepted = true
    self.accepted_at = DateTime.now
    self.status = 'active'
    self.save!
  end

  def worker
    proposal.business.user
  end
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :set_job_offer, only: [:show, :edit, :update, :destroy, :accept]

  # GET /job_offers
  # GET /job_offers.json
  def index
    @job_offers = JobOffer.all
  end

  # GET /job_offers/1
  # GET /job_offers/1.json
  def show
  end

  # GET /job_offers/new
  def new
    @proposal = Proposal.find(params[:proposal_id])
    @job_offer = JobOffer.new(proposal_id: @proposal.id, request_id: @proposal.request.id)
  end

  # GET /job_offers/1/edit
  def edit
  end

  # POST /job_offers
  # POST /job_offers.json
  def create
    @proposal = Proposal.find(params[:job_offer][:proposal_id])
    @job_offer = JobOffer.new(job_offer_params)
    @job_offer.proposal = @proposal
    @job_offer.request = @proposal.request

    respond_to do |format|
      if @job_offer.save
        format.html { redirect_to @job_offer, notice: 'Job offer sent to worker.' }
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_offers/1
  # PATCH/PUT /job_offers/1.json
  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        format.html { redirect_to @job_offer, notice: 'Job offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_offers/1
  # DELETE /job_offers/1.json
  def destroy
    @job_offer.destroy
    respond_to do |format|
      format.html { redirect_to job_offers_url, notice: 'Job offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def accept
    respond_to do |format|
      if @job_offer.accept!
        format.html { redirect_to @job_offer, notice: 'Job offer Accepted!' }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :show, notice: 'Failed to accept job order' }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_offer_params
      params.fetch(:job_offer, {}).permit(:agreed_job_completion, :agreed_job_completion_unit, :agreed_price, :proposal_id, :agreed_payment_mode)
    end
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/views/job_offers/_form.html.erb
<div class='job-offer-form'>
  <%= form_for(job_offer) do |f| %>
    <% if job_offer.errors.any? %>
      <div id="error_explanation">
        <h4><%= pluralize(job_offer.errors.count, "error") %> prohibited this job_offer from being saved:</h4>

        <ul>
          <% job_offer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :proposal_id, value: params[:proposal_id] %>

    <div class='agreed-item row'>
      <strong class='col s12 m4'>THE PARTIES:</strong>
      <p class='class col s12 m8'>
        Requester: <%= @proposal.request.user.complete_name.upcase %>
        <br />
        Worker: <%= @proposal.business.name.upcase %>
      </p>
    </div>

    <div class='agreed-item row'>
      <div class='col s12 m4'>
        <strong>THE JOB:</strong>
      </div>
      <div class='col s12 m8'>
        <%= @proposal.request.service.type.capitalize %>
      </div>
    </div>

    <div class='agreed-item amount row'>
      <div class='col s12 m4'>
        <strong>THE AMOUNT:</strong>
      </div>

      <div class='col s12 m4'v>
        <div class='input-field'>
          <span class='prefix'> PHP </span>
          <%= f.text_field :agreed_price, value: @proposal.price_quotation, class: 'amount-input' %>
        </div>
      </div>

      <div class='col s12 m4'>
        <div class='input-field'>
          <%= f.select :agreed_payment_mode, class: 'select' do %>
            <% [['One-time Payment', 'single'], ['Hourly', 'hourly'], ['Daily', 'daily'], ['Monthly', 'monthly']].each do |c| -%>
              <%= content_tag(:option, c.first, value: c.last, selected: (c.last == @proposal.payment_mode)) %>
            <% end %>
          <% end %>
          <%= f.label :agreed_payment_mode %>
        </div>
      </div>

      <div class='col s12 m8 offset-m4'>
        <p class='grey-text'>
        Both parties agree on the amount above to be paid in full by <strong><%= @proposal.request.user.complete_name %></strong> to <strong><%= @proposal.business.name %></strong> when the job is completed including the deliverable if there is any. The amount specified above is for the entire work done with no subtractions or additional fees.
        </p>
      </div>

    </div>

    <div class='agreed-item row'>
      <strong class='col s12 m4'>THE TIME:</strong>


        <div class='input-field col s6 m4'>
          <%= f.select :agreed_job_completion do %>
            <% (0..29).each do |c| -%>
              <%= content_tag(:option, (c.zero? ? 'Any' : c), value: c, selected: (c == @proposal.job_delivery_estimate.to_i)) %>
            <% end %>
          <% end %>
          <%= f.label :agreed_job_completion %>
        </div>

        <div class='input-field col s6 m4'>
          <%= f.select :agreed_job_completion_unit do %>
            <% [['Days', 'days'], ['Hours', 'hours'], ['Months', 'months']].each do |c| -%>
              <%= content_tag(:option, c.first, value: c.last, selected: (c.last == @proposal.job_delivery_estimate_unit)) %>
            <% end %>
          <% end %>
          <%= f.label :agreed_job_completion_unit, 'Hours/Days/Months' %>
        </div>
        <p class='grey-text col s12 m8 offset-m4'> Both parties agree that the job must be completed including the deliverable if there is any within [insert hours/days] from now.  </p>
    </div>


    <div class="input-field row">
      <div class='col s12 m8 offset-m4'>
        <%= f.submit 'Send', class: 'btn col s12 m4 btn-large' %>
      </div>
    </div>
  <% end %>

</div>

app/views/job_offers/edit.html.erb
<h1>Editing Job Offer</h1>

<%= render 'form', job_offer: @job_offer %>

<%= link_to 'Show', @job_offer %> |
<%= link_to 'Back', job_offers_path %>

app/views/job_offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Offers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_offers.each do |job_offer| %>
      <tr>
        <td><%= link_to 'Show', job_offer %></td>
        <td><%= link_to 'Edit', edit_job_offer_path(job_offer) %></td>
        <td><%= link_to 'Destroy', job_offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Offer', new_job_offer_path %>

app/views/job_offers/new.html.erb
<% breadcrumb :new_job_offer, @job_offer %>

<div class='container'>
  <div class='section'>
    <h4>Job Offer</h4>

    <%= render 'form', job_offer: @job_offer %>  
  </div>
</div>

app/views/job_offers/show.html.erb
<% breadcrumb :new_job_offer, @job_offer %>
<% requester = @job_offer.request.user %>
<% business = @job_offer.proposal.business %>
<div class='container section'>
  <h4 class='text-thin'> Job Offer <small class='grey-text'><%= @job_offer.status.capitalize %></small></h4>
  <p class='grey-text'>
    Job order id #<%= @job_offer.id.to_s[0..5] %> as of <%= @job_offer.created_at.to_date %>
  </p>

  <div class='agreed-item row'>
    <strong class='col s12 m4'>THE PARTIES:</strong>
    <div class='class col s12 m8'>
      <p> Requester: <strong><%= @job_offer.request.user.complete_name.upcase %></strong> </p>

      <p>
        Worker:
        <strong> <%= @job_offer.proposal.business.name.upcase %> </strong>
        <% if @job_offer.is_accepted %>
          <span class='green-text'> (ACCEPTED AT <%= @job_offer.accepted_at.to_date %>) </span>
        <% else %>
          <span class='grey-text'> (Waiting to Accept) </span>
        <% end %>
      </p>
    </div>
  </div>

  <div class='agreed-item row'>
    <div class='col s12 m4'>
      <strong>THE JOB:</strong>
    </div>
    <div class='col s12 m8'>
      <strong><%= @job_offer.request.service.type.capitalize %></strong>
    </div>
  </div>

  <div class='agreed-item amount row'>
    <div class='col s12 m4'>
      <strong>THE AMOUNT:</strong>
    </div>

    <div class='col s12 m8'v>
      <div class=''>
        <strong class=''> <%= number_to_currency(@job_offer.agreed_price, unit: 'PHP') %></strong>
      </div>
      <p class='grey-text'>
      Both parties agree on the amount of <strong><%= number_to_currency(@job_offer.agreed_price, unit: 'PHP') %></strong> to be paid in full by <strong><%= requester.complete_name %></strong> to <strong><%= business.name %></strong> when the job is completed including the deliverable if there is any. The amount specified above is for the entire work done with no subtractions or additional fees.
      </p>
    </div>
  </div>

  <div class='agreed-item row'>
    <strong class='col s12 m4'>THE TIME:</strong>
    <div class='col s12 m8'>
      <div class=''>
        <strong><%= @job_offer.agreed_job_completion %> <%= @job_offer.agreed_job_completion_unit %></strong>
      </div>
      <p class='grey-text'> Both parties agree that the job must be completed including the deliverable if there is any within <strong><%= @job_offer.agreed_job_completion %> <%= @job_offer.agreed_job_completion_unit %></strong> from now.  </p>
    </div>
  </div>

  <div class='center-align'>
    <% if !@job_offer.is_accepted && current_user == @job_offer.worker %>
      <%= link_to 'ACCEPT OFFER', accept_job_offer_path(@job_offer), class: 'btn btn-large', method: :post %>
    <% end %>
  </div>

</div>